# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('art', models.URLField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('track_type', models.CharField(choices=[('DJ', "DJ's track"), ('R', 'A request')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpacastats.Track'),
        ),
    ]
