# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alpacastats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 2, 20, 15, 28, 55, 656732, tzinfo=utc), verbose_name='date'),
            preserve_default=False,
        ),
    ]
