# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpacastats', '0004_auto_20160220_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='track',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='vote',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpacastats.Track'),
        ),
    ]
