# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpacastats', '0005_auto_20160220_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
