# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alpacastats', '0006_vote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 21, 2, 2, 58, 565629, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 21, 2, 3, 7, 81233, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
