# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpacastats', '0007_auto_20160221_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='played',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
